### ISSUE TITLE
山寨这个币以后挖矿挖到全部币后出块速度太快怎么解决?

### ISSUE THREAD

**Issue by kkmg112400** [imharrywu/fastcoin#2]
按照http://blog.csdn.net/hacode/article/details/40422535  的教程山寨后生成了新的币 而且预挖了全部币以后出块太快 怎么解决?

**Comment by imharrywu** [comment]
mining will speed down automatically, after several intervals( 2016blocks/interval).

**Comment by HuiguoRose** [comment]
ok , 3q
